// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7VFIJXeKDKl1PPN5tLVXr3ljLWSsyau0',
    appId: '1:783634635213:web:98e2990eb1fc3aaec54c84',
    messagingSenderId: '783634635213',
    projectId: 'query-box-eea9f',
    authDomain: 'query-box-eea9f.firebaseapp.com',
    storageBucket: 'query-box-eea9f.appspot.com',
    measurementId: 'G-WC3P5M7TK4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ2QsVowflT2zBO_Q6KYlPjQCbCunAwKk',
    appId: '1:783634635213:android:ceeb5c503b9949ffc54c84',
    messagingSenderId: '783634635213',
    projectId: 'query-box-eea9f',
    storageBucket: 'query-box-eea9f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPrQibOe0jt9dLmQAyol0KQRVwHGPWhZI',
    appId: '1:783634635213:ios:95d37700f969080bc54c84',
    messagingSenderId: '783634635213',
    projectId: 'query-box-eea9f',
    storageBucket: 'query-box-eea9f.appspot.com',
    iosBundleId: 'com.example.queryBoxEnquiryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPrQibOe0jt9dLmQAyol0KQRVwHGPWhZI',
    appId: '1:783634635213:ios:95d37700f969080bc54c84',
    messagingSenderId: '783634635213',
    projectId: 'query-box-eea9f',
    storageBucket: 'query-box-eea9f.appspot.com',
    iosBundleId: 'com.example.queryBoxEnquiryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7VFIJXeKDKl1PPN5tLVXr3ljLWSsyau0',
    appId: '1:783634635213:web:1f557c662bf05d18c54c84',
    messagingSenderId: '783634635213',
    projectId: 'query-box-eea9f',
    authDomain: 'query-box-eea9f.firebaseapp.com',
    storageBucket: 'query-box-eea9f.appspot.com',
    measurementId: 'G-GPH21FW66K',
  );

}